// Run with: npx tsx scripts/genRegistryDoc.ts
// Reads the registered buffers + systems by importing the canonical registration
// module and renders docs/REGISTRY.md so future agents can grep before adding.

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { createRegistry } from "../src/runtime/registry";
import { registerCoreBuffers } from "../src/buffers";
import { registerCoreSystems } from "../src/systems";

function table(rows: string[][]): string {
  if (rows.length === 0) return "_(none registered)_";
  const header = rows[0];
  const sep = header.map(() => "---");
  const body = rows.slice(1);
  const fmt = (r: string[]) => `| ${r.map((c) => c.replace(/\|/g, "\\|")).join(" | ")} |`;
  return [fmt(header), fmt(sep), ...body.map(fmt)].join("\n");
}

const reg = createRegistry();
registerCoreBuffers(reg);
registerCoreSystems(reg);

const buffers = reg.listBuffers();
const systems = reg.listSystems();

const bufferRows: string[][] = [["id", "description", "written by", "read by"]];
for (const b of buffers) {
  const writtenBy: string[] = [];
  const readBy: string[] = [];
  for (const s of systems) {
    for (const ba of s.buffers) {
      if (ba.id !== b.id) continue;
      if (ba.access === "write" || ba.access === "readwrite") writtenBy.push(s.id);
      if (ba.access === "read" || ba.access === "readwrite") readBy.push(s.id);
    }
  }
  bufferRows.push([
    "`" + b.id + "`",
    b.description.replace(/\s+/g, " ").trim(),
    writtenBy.length ? writtenBy.map((x) => "`" + x + "`").join(", ") : "—",
    readBy.length ? readBy.map((x) => "`" + x + "`").join(", ") : "—",
  ]);
}

const systemRows: string[][] = [["id", "description", "reads", "writes", "ordering"]];
for (const s of systems) {
  const reads = s.buffers.filter((b) => b.access === "read" || b.access === "readwrite").map((b) => "`" + b.id + "`");
  const writes = s.buffers.filter((b) => b.access === "write" || b.access === "readwrite").map((b) => "`" + b.id + "`");
  const ordering: string[] = [];
  if (s.runsAfter && s.runsAfter.length) ordering.push("after: " + s.runsAfter.map((x) => "`" + x + "`").join(", "));
  if (s.runsBefore && s.runsBefore.length) ordering.push("before: " + s.runsBefore.map((x) => "`" + x + "`").join(", "));
  systemRows.push([
    "`" + s.id + "`",
    s.description.replace(/\s+/g, " ").trim(),
    reads.length ? reads.join(", ") : "—",
    writes.length ? writes.join(", ") : "—",
    ordering.length ? ordering.join("; ") : "—",
  ]);
}

const doc = `# Runtime Registry

> **This file is generated by \`npm run registry\`. Do not edit by hand.**
>
> Source of truth: \`src/buffers/\` and \`src/systems/\`. Re-run the script
> after adding or modifying any buffer or system.

## Buffers

${table(bufferRows)}

## Systems

${table(systemRows)}

## How to use this index

Before adding a new buffer or system, search this file for an existing entry
that already covers your need. The runtime won't stop you from adding
duplicates, but the result will be more code to maintain and conflicting
sources of truth.

If you do add something new:
1. Update the relevant file in \`src/buffers/\` or \`src/systems/\`.
2. Run \`npm run registry\`.
3. Add a test in \`tests/buffers/\` or \`tests/systems/\`.
`;

const outDir = resolve("docs");
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "REGISTRY.md"), doc);
console.log(`wrote docs/REGISTRY.md (${buffers.length} buffers, ${systems.length} systems)`);
